typography_spectrum: 0.8966202775423074
color:
  brandStrength: 0.4539584759742686
  lightness: 0.7136917739008359
  saturation: 0.2918384569338384
  rhythmicContrast: 0.8608991363061832
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
github: true
layout_spectrum: 0.5634392274372133
author:
  name: Kris Hansen
name: helpalex
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
title: Help Alex
content: []
description: Alex needs urgent bone marrow transplant - Are you a match?
purpose:
  - type: internal
    label: Fill out a donor contact form
    item: 7007957e-65d1-4f5f-bedb-b3ec4ddfd53c
