typography_spectrum: 0.8966202775423074
color:
  brandStrength: 0.4539584759742686
  lightness: 0.7136917739008359
  saturation: 0.2918384569338384
  rhythmicContrast: 0.8608991363061832
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
github: true
layout_spectrum: 0.5634392274372133
author:
  name: Kris Hansen
name: helpalex
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
title: Help Alex
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: article
    html: >-
      <article><h1>Playground Swings photo by Aaron Burden (@aaronburden) on
      Unsplash</h1><p>Download this free HD photo of swing, playground, park and
      play by Aaron Burden (@aaronburden)</p><img
      src="http://images.unsplash.com/photo-1436915947297-3a94186c8133?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&s=df1130c57c024c684749ce7eba4006e7"></article>
    src: >-
      http://images.unsplash.com/photo-1436915947297-3a94186c8133?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&s=df1130c57c024c684749ce7eba4006e7
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://unsplash.com'
        name: Unsplash
        favicon: 'https://unsplash.com/favicon.ico'
        domain: unsplash.com
      keywords: []
      description: >-
        Download this free HD photo of swing, playground, park and play by Aaron
        Burden (@aaronburden)
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      isBasedOnUrl: 'https://unsplash.com/photos/ob6O_xd67O0'
      title: Playground Swings photo by Aaron Burden (@aaronburden) on Unsplash
      datePublished: null
    title: Playground Swings photo by Aaron Burden (@aaronburden) on Unsplash
    caption: >-
      Download this free HD photo of swing, playground, park and play by Aaron
      Burden (@aaronburden)
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Alex needs urgent bone marrow transplant - Are you a match?
purpose:
  - type: internal
    label: Contact Form
    item: 7007957e-65d1-4f5f-bedb-b3ec4ddfd53c
